#ifndef BINDING_POINTS_H
#define BINDING_POINTS_H

#define CAMERA_BUFFER_BINDING						0
#define SUN_BUFFER_BINDING							1
#define SHADOW_TRANSFORM_BUFFER_BINDING				2
#define TILE_LIGHT_MAP_BUFFER_BINDING				3
#define TILE_LIGHT_BUFFER_BINDING					4
#define TILE_LIGHT_TRANSFORM_BUFFER_BINDING			5
#define CAR_LIGHTING_BUFFER_BINDING					6
#define TILE_LIGHT_SHADOW_TRIANGLE_BUFFER_BINDING	7
#define VERTEX_BUFFER_BINDING						8
#define INDEX_BUFFER_BINDING						9

#endif // !BINDING_POINTS_H