#ifndef SCENE_CONSTANCES_H
#define SCENE_CONSTANCES_H

#define MAX_CAR_CNT 512
#define MAX_LIGHT_PER_CAR 24
#define LIGHT_MAP_SIZE_X 134
#define LIGHT_MAP_SIZE_Y 122
#define LIGHT_MAP_GRID_LENGTH 1600.0f

#endif // !SCENE_CONSTANCES_H
