#ifndef SCENE_CONSTANCES_H
#define SCENE_CONSTANCES_H

#define SUN_RADIUS_DIST_RATIO (1.0f / 214)
#define MAX_CAR_CNT 512
#define MAX_LIGHT_PER_CAR 24
#define LIGHT_MAP_SIZE_X 134
#define LIGHT_MAP_SIZE_Y 122
#define LIGHT_MAP_GRID_LENGTH 18.0f

#endif // !SCENE_CONSTANCES_H
