#include "lighting_night_defines.h"

layout(std430, binding = VERTEX_BUFFER_BINDING) buffer vertex_block
{ 
    float vertices[];
};

layout(std430, binding = INDEX_BUFFER_BINDING) buffer index_block
{ 
    uint indices[];
};

layout (local_size_x = 64) in;

uniform int num_triangles;

void main()
{
    uint triangle_idx = gl_GlobalInvocationID.x;
	if(triangle_idx >= num_triangles)
	{
		return;
	}
	vec3 positions[3];
	uint vert_idx[3];
	for(uint i = 0; i < 3; i++)
	{
		vert_idx[i] = indices[3 * triangle_idx + i];
		uint offset = 3 * vert_idx[i];
		positions[i] = vec3(vertices[offset], vertices[offset + 1], vertices[offset + 2]);
	}
	vec2 minCoord = positions[0].xy;
	vec2 maxCoord = minCoord;
	minCoord = min(minCoord, positions[1].xy);
	minCoord = min(minCoord, positions[2].xy);
	maxCoord = max(maxCoord, positions[1].xy);
	maxCoord = max(maxCoord, positions[2].xy);
	ivec2 startIdx = ivec2(minCoord / LIGHT_MAP_GRID_LENGTH + vec2(0.5 * LIGHT_MAP_SIZE_X, 0.5 * LIGHT_MAP_SIZE_Y) -1);
	ivec2 endIdx = ivec2(maxCoord / LIGHT_MAP_GRID_LENGTH + vec2(0.5 * LIGHT_MAP_SIZE_X, 0.5 * LIGHT_MAP_SIZE_Y) + 1);

	int i = startIdx.x;
	int j = startIdx.y;
	int gird_idx = i * LIGHT_MAP_SIZE_Y + j;
	int k = tile_light_map.idx_range[gird_idx].x - 1;
	int end = tile_light_map.idx_range[gird_idx].y;
	while(true)
	{
		k++;
		while(k == end)
		{
			j++;
			if(j > endIdx.y)
			{
				i++;
				if(i > endIdx.x)
				{
					return;
				}
				j = startIdx.y;
			}
			gird_idx = i * LIGHT_MAP_SIZE_Y + j;
			k = tile_light_map.idx_range[gird_idx].x;
			end = tile_light_map.idx_range[gird_idx].y;	
		}
		int layer = findTileLightShadowLayer(k);
		if(layer >= NUM_TILE_LIGHT_SHADOW_LAYERS)
		{
			continue;
		}
		vec3 normal = cross(positions[1] - positions[0], positions[2] - positions[0]);
		if(dot(normal, tile_lights[k].position.xyz - positions[0]) <= 0)
		{
			continue;
		}
		vec4 pos[3];
		for(int p = 0; p < 3; p++)
		{
			pos[p] = tile_lights[k].view_proj * vec4(positions[p], 1.0);
		}
		if(pos[0].x >= pos[0].w && pos[1].x >= pos[1].w && pos[2].x >= pos[2].w ||
			pos[0].x <= -pos[0].w && pos[1].x <= -pos[1].w && pos[2].x <= -pos[2].w ||
			pos[0].y >= pos[0].w && pos[1].y >= pos[1].w && pos[2].y >= pos[2].w ||
			pos[0].y <= -pos[0].w && pos[1].y <= -pos[1].w && pos[2].y <= -pos[2].w ||
			pos[0].z >= pos[0].w && pos[1].z >= pos[1].w && pos[2].z >= pos[2].w ||
			pos[0].z <= -pos[0].w && pos[1].z <= -pos[1].w && pos[2].z <= -pos[2].w)
		{
			continue;
		}
		vec2 test[3];
		for(int p = 0; p < 3; p++)
		{
			test[p] = pos[p].xy / (pos[p].w == 0.0 ? -1e-6 : pos[p].w);
		}
		bool surroundTest[3] = { (test[0].x * test[1].y - test[0].y * test[1].x) * pos[2].w > 0,
								(test[1].x * test[2].y - test[1].y * test[2].x) * pos[0].w > 0,
								(test[2].x * test[0].y - test[2].y * test[0].x) * pos[1].w > 0 };
		bool isIn = surroundTest[0] == surroundTest[1] && surroundTest[0] == surroundTest[2];
		for(int p = 0; p < 3 && !isIn; p++)
		{
			vec2 a = test[p];
			int p2 = (p + 1) % 3;
			vec2 v = test[p2] - a;
			float lt2 = dot(a, a);
			if(pos[p2].w < 0)
			{
				if(pos[p].w < 0)
				{
					continue;
				}
				lt2 = min(lt2, 1.0);
				v = -v;
			}
			else if(pos[p].w < 0)
			{
				a = test[p2];
				lt2 = min(dot(a, a), 1.0);
			}
			float t = v.x * a.y - v.y * a.x;
			isIn = lt2 < 1.0 || dot(v, a) < 0 && dot(v, v) > max(t * t, lt2 - 1);
		}
		if(isIn)
		{
			int layer_triangle_idx = atomicAdd(tile_light_shadow_triangles.commands[layer].count, 3) / 3;
			layer_triangle_idx += MAX_AVERANGE_TRIANGLES_PER_LIGHT * tileLightShadowLayerOffset(layer);
			tile_light_shadow_triangles.triangles[layer_triangle_idx] = TileLightShadowTriangle(vert_idx, k);
		}
	}
}
